#! /bin/sh
#
#       <CLEANUP-SCRIPT>
#
#       Script called in the event that a fetch_logs script fails
#
#       Copyright 2016 Dell Inc.
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

#check the /mnt mount point
mount | grep "/mnt" 2>/dev/null
if [ $? -eq 0 ];then
    umount /mnt
fi

#revert the mount points
mount -o remount,$MOUNT_PROPERTY /cdrom
