#!/bin/sh
#
#       <SUCCESS-SCRIPT>
#
#       Called in the event that postinstall (chroot) steps complete successfully
#
#       Copyright 2008-2010 Dell Inc.
#           Mario Limonciello <Mario_Limonciello@Dell.com>
#           Hatim Amro <Hatim_Amro@Dell.com>
#           Michael E Brown <Michael_E_Brown@Dell.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

# BE AWARE THAT THIS SCRIPT IS CALLED FROM OUTSIDE THE CHROOT.
# The OS is mounted under $TARGET

. /usr/share/dell/scripts/fifuncs "target"

set -x
set -e

IFHALT "(SUCCESS) Clean-Up .."

#This will be rebuilt before OEM config
rm -f $TARGET/etc/apt/sources.list.d/dell.list

if [ "$BOOTDEV" = "$TARGETDEV" ]; then
    if [ -d "/isodevice" ]; then
        RP="/isodevice"
    else
        RP="/cdrom"
    fi
    mount -o remount,rw $RP
    IFHALT "Resetting grub fail state"
    [ -s $RP/grub/grubenv ] || rm -f $RP/grub/grubenv
    mkdir -p $RP/grub
    grub-editenv $RP/grub/grubenv unset recordfail

    #Set the right partition active now that we're done
    /tmp/set_active_partition

    IFHALT "Clean up FI Env..."
    rm -rf $RP/scripts/chroot-scripts/os-post/95-set_UTC_TZ.sh
    rm -rf $RP/misc/dell-unsupported.py
    rm -rf $RP/misc/run-tz-fix
    rm -rf $RP/misc/tz_offset.py
    rm -rf $RP/misc/drmk.zip
    rm -rf $RP/command.com
    rm -rf $RP/autoexec.bat
    rm -rf $RP/dellbio.bin
    rm -rf $RP/dellrmk.bin
    rm -rf $RP/linld.com
    rm -rf $RP/cmd.cfg
    rm -rf $RP/up.zip
    rm -rf $RP/up.tgz
    rm -rf $RP/upimg.bin
    rm -rf $RP/upimg.gz
    rm -rf $RP/SDR
    rm -rf $RP/*.SDR
    rm -rf $RP/srv

    IFHALT "Report the LOG..."
    if [ -f /dell/fist/tal ]; then
        cp $TARGET/$LOG/chroot.sh.log /tmp/fist.log
        /dell/fist/tal PutFiles /tmp/fist.log
        rm -rf /cdrom/debs/fist
    fi

    #If we have another script to run, do it
    if [ -f $RP/scripts/chroot-scripts/SUCCESS-SCRIPT ]; then
        $RP/scripts/chroot-scripts/SUCCESS-SCRIPT
        rm -f $RP/scripts/chroot-scripts/SUCCESS-SCRIPT
        rm -f $RP/scripts/chroot-scripts/FAIL-SCRIPT
        IFHALT "(SUCCESS) Report to logs.. Done!"
    fi

    #Check if we'll display OIE
    if grep -q oie /proc/cmdline 2>&1 >/dev/null; then
        /usr/share/dell/oie/oie.py pass
    fi
fi

IFHALT "(SUCCESS) Clean-Up .. Done!"
