#!/bin/bash -e

# for prepare_grub_to_access_device
. /usr/lib/grub/update-grub_lib

GRUB_IMAGE_PATH=/usr/share/images/grub
bg=dell-wallpaper-640x480.png

# check for usable backgrounds
use_bg=false
if [ "$GRUB_TERMINAL" = "gfxterm" ] ; then
  prepare_grub_to_access_device `${grub_probe} --target=device ${GRUB_IMAGE_PATH}`
  if [ -f ${GRUB_IMAGE_PATH}/$bg ] ; then 
      echo "Found Dell background: ${bg}" >&2
      use_bg=true
  fi
fi

# set the background if possible
if ${use_bg} ; then
  case ${bg} in
    *.png)		reader=png ;;
    *.tga)		reader=tga ;;
    *.jpg|*.jpeg)	reader=jpeg ;;
  esac
  cat << EOF
insmod ${reader}
if background_image ${GRUB_IMAGE_PATH}/${bg} ; then
  set color_normal=white/black
  set color_highlight=black/white
  set menu_color_normal=white/black
  set menu_color_highlight=black/white
fi
EOF
fi
