#!/bin/bash -e

# for convert_system_path_to_grub_path()
source /usr/lib/grub/update-grub_lib

# check for usable backgrounds
use_bg=false
if [ "$GRUB_TERMINAL" = "gfxterm" ] ; then
  for i in /usr/share/images/grub/dell-wallpaper-640x480.png ; do
    if bg=`convert_system_path_to_grub_path $i` ; then 
      echo "Found Dell background: `basename ${bg}`" >&2
      use_bg=true
      break
    fi
  done
fi

# set the background if possible
if ${use_bg} ; then
  case ${bg} in
    *.png)		reader=png ;;
    *.tga)		reader=tga ;;
    *.jpg|*.jpeg)	reader=jpeg ;;
  esac
  cat << EOF
insmod ${reader}
if background_image ${bg} ; then
  set color_normal=white/black
  set color_highlight=black/white
  set menu_color_normal=white/black
  set menu_color_highlight=black/white
fi
EOF
fi
