#!/bin/bash -e

source /usr/lib/grub/grub-mkconfig_lib

cat << EOF
#NOTE: These are the main means for recovery.  In the event of a power loss during recovery, 
#      grub is installed on the recovery partition, and will be loaded (in english) with
#      these same entries available to it.
menuentry "Reinstall Operating System (WARNING: all data will be LOST!)" {
	linux	(hd0,2)/casper/vmlinuz preseed/file=/cdrom/preseed/dell.seed boot=casper REINSTALL automatic-ubiquity noprompt edd=on quiet splash
	initrd	(hd0,2)/casper/initrd.gz
}
EOF

