#!/bin/bash -e

# for convert_system_path_to_grub_path()
source /usr/lib/grub/update-grub_lib

#Build chinese recovery entries.
cat << EOF
#NOTE: These are the main means for recovery.  In the event of a power loss during recovery, 
#      grub is installed on the recovery partition, and will be loaded (in english) with
#      these same entries available to it.
menuentry "Reinstall Ubuntu Linux Operating System" {
#menuentry "重装 Ubuntu  Linux 操作系统" {
	linux	(hd0,2)/casper/vmlinuz preseed/file=/cdrom/preseed/dell.seed boot=casper REINSTALL automatic-ubiquity noprompt edd=on quiet splash
	initrd	(hd0,2)/casper/initrd.gz
}
EOF

