#!/bin/bash -e

source /usr/lib/grub/grub-mkconfig_lib

cat << EOF
menuentry "Restore #OS# to factory state" {
        set root='(hd0,#PARTITION#)'
	search --no-floppy --fs-uuid --set #UUID#
	linux	/casper/vmlinuz preseed/file=/cdrom/preseed/ubuntu.seed boot=casper automatic-ubiquity noprompt quiet splash dell-recovery/recovery_type=hdd -- #EXTRA#
	initrd	/casper/initrd.lz
}
EOF

