#!/bin/bash -e

source /usr/lib/grub/grub-mkconfig_lib

cat << EOF
menuentry "Restore #OS# to factory state" {
        set root='(hd0,#PARTITION#)'
	search --no-floppy --fs-uuid --set #UUID#
        source  /grub/common.cfg
        linux   /casper/vmlinuz dell-recovery/recovery_type=hdd \$options
	initrd	/casper/initrd.lz
}
EOF

