FROM ubuntu:eoan

RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
	build-essential \
	debhelper \
	dh-python \
	dpkg-dev \
	python3 \
	python3-distutils-extra \
	po-debconf \
	pyflakes3 \
	lsb-release \
	gnu-efi
RUN mkdir -p /build/dell-recovery
WORKDIR /build/dell-recovery

CMD ["dpkg-buildpackage", "-tc", "-us", "-uc"]
