#!/bin/sh
set -e

case "$1" in
	configure)
		if test -d /var/lib/update-notifer/user.d; then
			cp -f /usr/share/dell/notes/create-dell-recovery-media.note \
			      /var/lib/update-notifer/user.d
		fi
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \'$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
